server {
    listen 80;

    location / {
        root /var/www/tactitok;
        index placeholder.html;
        try_files $uri $uri/ =404;
    }

    location /api/ {
        proxy_pass http://172.20.10.2:8080/;
        proxy_set_header Host 172.20.10.2;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
    }
}