server {
    listen 80;

    location / {
        root /var/www/tactitok;
        index placeholder.html;
        try_files $uri $uri/ =404;
    }

    location /api/ {
        proxy_pass https://jsonplaceholder.typicode.com/;
        proxy_set_header Host jsonplaceholder.typicode.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}